[target.aarch64-linux-android]
linker = "C:\\Users\\Otuo\\AppData\\Local\\Android\\Sdk\\ndk\\28.0.12674087\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android21-clang++.cmd"


[target.armv7-linux-androideabi]
linker = "C:\\Users\\Otuo\\AppData\\Local\\Android\\Sdk\\ndk\\28.0.12674087\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-androideabi21-clang++.cmd"

