[target.aarch64-linux-android]
linker = "/media/kofi/5A5469075468E76B/Users/ubuntu/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++"
runner = "./run-on-android.sh"

[target.armv7-linux-androideabi]
linker = "/media/kofi/5A5469075468E76B/Users/ubuntu/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang++"
runner = "./run-on-android.sh"