[target.aarch64-linux-android]
linker = "C:\\Users\\taimoor\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin/aarch64-linux-android21-clang++.cmd"
#runner = "./run-on-android.sh"

[target.armv7-linux-androideabi]
linker = "C:\\Users\\taimoor\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin/armv7a-linux-androideabi21-clang++.cmd"
#runner = "./run-on-android.sh"