// Automatically generated by flapigen
package com.example.swift_final.lib;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public final class Authentication {

    public Authentication(@NonNull String username, @Nullable String password) {
        mNativeObj = init(username, password);
    }
    private static native long init(@NonNull String username, @Nullable String password);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Authentication(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}