// Automatically generated by flapigen
package com.example.swift_final.lib;
import androidx.annotation.NonNull;

public final class Downloader {

    public static @NonNull java.util.Optional<RequestInfo> getRequestInfo(@NonNull DownloadInfo download_info, @NonNull DownloadCallback download_callback) {
        long a0 = download_info.mNativeObj;
        long ret = do_getRequestInfo(a0, download_callback);
        java.util.Optional<RequestInfo> convRet;
        if (ret != 0) {
            convRet = java.util.Optional.of(new RequestInfo(InternalPointerMarker.RAW_PTR, ret));
        } else {
            convRet = java.util.Optional.empty();
        }

        JNIReachabilityFence.reachabilityFence1(download_info);

        return convRet;
    }
    private static native long do_getRequestInfo(long download_info, DownloadCallback download_callback);

    private Downloader() {}
}