// Automatically generated by flapigen
package com.example.swift_final.lib;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public final class DownloadInfo {

    public DownloadInfo(@NonNull String url, @Nullable Authorisation auth) {
        long a1 = 0;//TODO: use ptr::null() for corresponding constant
        if (auth != null) {
            a1 = auth.mNativeObj;
            auth.mNativeObj = 0;
        }

        mNativeObj = init(url, a1);
        JNIReachabilityFence.reachabilityFence1(auth);
    }
    private static native long init(@NonNull String url, long auth);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ DownloadInfo(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}