// Automatically generated by flapigen
package com.example.swift_final.lib;
import androidx.annotation.NonNull;

public interface DownloadCallback {


    void responseError(@NonNull ResponseErrors error);


    void statusError(int error_code, @NonNull String reason);


    boolean isActive();

}
