// Automatically generated by flapigen
package com.example.swift_final.lib;
import androidx.annotation.NonNull;

public final class FileType {

    public FileType(@NonNull String extension) {
        mNativeObj = init(extension);
    }
    private static native long init(@NonNull String extension);

    public final TypeOfFile getType() {
        int ret = do_getType(mNativeObj);
        TypeOfFile convRet = TypeOfFile.fromInt(ret);

        return convRet;
    }
    private static native int do_getType(long self);

    public static FileCategory getCategory(@NonNull TypeOfFile type_of_file) {
        int a0 = type_of_file.getValue();
        int ret = do_getCategory(a0);
        FileCategory convRet = FileCategory.fromInt(ret);

        JNIReachabilityFence.reachabilityFence1(type_of_file);

        return convRet;
    }
    private static native int do_getCategory(int type_of_file);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ FileType(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}