// Automatically generated by flapigen
package com.example.swift_final.lib;


public enum FileCategory {
    Video(0),
    Document(1),
    Image(2),
    Compressed(3),
    Audio(4),
    Application(5),
    Other(6);

    private final int value;
    FileCategory(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static FileCategory fromInt(int x) {
        switch (x) {
            case 0: return Video;
            case 1: return Document;
            case 2: return Image;
            case 3: return Compressed;
            case 4: return Audio;
            case 5: return Application;
            case 6: return Other;
            default: throw new Error("Invalid value for enum FileCategory: " + x);
        }
    }
}
