// Automatically generated by flapigen
package com.example.swift_final.lib;


public final class Logger {
    /**
     * Set up logging
     */
    public static native void initialiseLogging();

    private Logger() {}
}