// Automatically generated by flapigen
package com.example.swift_final.lib;


public enum ResponseErrors {
    ErrorParsingRequest(0),
    UnableToDecodeRequest(1),
    RedirectedManyTimes(2),
    ConnectionTimeout(3),
    UnknownError(4);

    private final int value;
    ResponseErrors(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static ResponseErrors fromInt(int x) {
        switch (x) {
            case 0: return ErrorParsingRequest;
            case 1: return UnableToDecodeRequest;
            case 2: return RedirectedManyTimes;
            case 3: return ConnectionTimeout;
            case 4: return UnknownError;
            default: throw new Error("Invalid value for enum ResponseErrors: " + x);
        }
    }
}
