// Automatically generated by flapigen
package com.example.swift_final.lib;


public enum TypeOfFile {
    Word(0),
    Excel(1),
    PowerPoint(2),
    Jpg(3),
    Mkv(4),
    Png(5),
    Html(6),
    MpFour(7),
    Pdf(8),
    Other(9),
    Application(10),
    Audio(11),
    MpThree(12),
    Gif(13),
    Video(14),
    Zip(15),
    Image(16),
    Iso(17),
    ThreeGp(18),
    Flv(19),
    Document(20),
    Compressed(21);

    private final int value;
    TypeOfFile(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static TypeOfFile fromInt(int x) {
        switch (x) {
            case 0: return Word;
            case 1: return Excel;
            case 2: return PowerPoint;
            case 3: return Jpg;
            case 4: return Mkv;
            case 5: return Png;
            case 6: return Html;
            case 7: return MpFour;
            case 8: return Pdf;
            case 9: return Other;
            case 10: return Application;
            case 11: return Audio;
            case 12: return MpThree;
            case 13: return Gif;
            case 14: return Video;
            case 15: return Zip;
            case 16: return Image;
            case 17: return Iso;
            case 18: return ThreeGp;
            case 19: return Flv;
            case 20: return Document;
            case 21: return Compressed;
            default: throw new Error("Invalid value for enum TypeOfFile: " + x);
        }
    }
}
